name: Run Tests

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 11 (IMPORTANT)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run Tests
        run: mvn clean test
